# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

project 'Device_Server/Smart_Device_Server.xcodeproj'

target 'Smart_Device_Server' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Smart_Device_Server

    pod 'CocoaAsyncSocket'

end
