# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HUDDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HUDDemo
  pod 'LookinServer', :configurations => ['Debug']

  target 'HUDDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HUDDemoUITests' do
    # Pods for testing
  end

end
