# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Socket_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'
  pod 'AFNetwork'

  # Pods for Socket_Test

end
