additional_guides:
    - https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation
    - https://github.com/gali8/Tesseract-OCR-iOS/wiki/Using-Tesseract-OCR-iOS
    - https://github.com/gali8/Tesseract-OCR-iOS/wiki/Tips-&-Tricks-(Improving-OCR-Results)
