source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pod_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pod_test
  pod 'react-native-blur', '~> 0'
  pod 'react-native-geolocation', '~> 2.0.2'

end
